### ISSUE TITLE
Unable to activate on Blender 3.6.18

### ISSUE THREAD

**Issue by connomar** [Devinci297/MSFS-LOD-Maker#4]
Having installed the zip download into Blender, the activate tick box generates an error.  It appears that the lodify_addon.log file is attempting to generate in the windows\system32 folder.  Not surprisingly, Windows won't let it.

I have search the python files for hard coding of this path without success.  Thanks for your work.

**Comment by connomar** [comment]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender3.6LTS_3.6.18.0_x64__ppwjx1n5r4v9t\Blender\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MSFS-LOD-Maker\__init__.py", line 40, in register
    setup_logging()
  File "C:\Users\Martin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MSFS-LOD-Maker\__init__.py", line 34, in setup_logging
    logging.basicConfig(filename='lodify_addon.log', level=logging.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender3.6LTS_3.6.18.0_x64__ppwjx1n5r4v9t\Blender\3.6\python\lib\logging\__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender3.6LTS_3.6.18.0_x64__ppwjx1n5r4v9t\Blender\3.6\python\lib\logging\__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender3.6LTS_3.6.18.0_x64__ppwjx1n5r4v9t\Blender\3.6\python\lib\logging\__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'C:\\WINDOWS\\system32\\lodify_addon.log'

**Comment by MonAssistantNumerique62** [comment]
Same problem here with blender 3.3

**Comment by MonAssistantNumerique62** [comment]
Same problem here with Blender 3.3, but with the following path : C:\Program Files\Blender Foundation\Blender 3.3

I managed to activate the add-ons by modifiing the access rights for that folder. I give "everyone" a full access.

**Comment by Devinci297** [comment]
I'm not sure what the difference is from 3.3 to 3.6 but it should've worked since I tried it on 4.2 it was good as well.

**Comment by MonAssistantNumerique62** [comment]
Yes it works, but by default the plugin can't write in the Blender folder. It's a Windows restriction. It is needed for the users to give the appropriate access rights to the folder where Blender is installed. Perhaps can you place that log file in another folder (documents or temp) ? It will ease the installation for people that don't know how to change folders access rights. If not, they have the solution in that thread.

**Comment by UNC1RLM** [comment]
New at this.. I have tried everything to install this app from zip and just pasting and i get error messages.  I tried zip and didn't get an error but I can't find it either to tick it. I have given access writes to everyone for all folders in blender.

<img width="796" height="865" alt="Image" src="https://github.com/user-attachments/assets/828eaeb7-65cb-4b67-992f-74032b8b3cde" />
<img width="994" height="401" alt="Image" src="https://github.com/user-attachments/assets/2e58b839-54db-4f02-b1dd-5e1a77629d05" />
<img width="1056" height="400" alt="Image" src="https://github.com/user-attachments/assets/92c247c9-5e2a-4b51-90d9-21b09821c4ca" />

**Comment by Devinci297** [comment]
> New at this.. I have tried everything to install this app from zip and just pasting and i get error messages. I tried zip and didn't get an error but I can't find it either to tick it. I have given access writes to everyone for all folders in blender.
> 
Hello, 
Sorry I've been out of Blender for a while, I just released a new version can you try it and let me know if you're able to enable it in Blender 3.6?

**Comment by UNC1RLM** [comment]
This is 3.6.16 and nothing..i try install by the zip and nothing shows up (not sure what the name displayed is list is supposed to be but not found to tick it. Tried to paste in scripts addon and it show up in Capital letters? but don't see it in list to tick. I changed all property to access for everyone in all Blender 3.3/3.6.16 and tried 4.2 but nothing (install by disk and zip file).

<img width="766" height="908" alt="Image" src="https://github.com/user-attachments/assets/e6d86a76-3fbe-4f9c-88cd-68ba2aba15d1" />
<img width="1227" height="274" alt="Image" src="https://github.com/user-attachments/assets/73684846-6657-4bfe-97f3-4c5f98d54978" />
<img width="1227" height="274" alt="Image" src="https://github.com/user-attachments/assets/bf6f66e0-3325-427d-85d7-32ae41dcab97" />
<img width="766" height="908" alt="Image" src="https://github.com/user-attachments/assets/f442b292-1fb0-4b18-b663-00d4773f5bbb" />
<img width="1347" height="795" alt="Image" src="https://github.com/user-attachments/assets/581f56f1-85d4-4775-915b-6605b354b283" />

**Comment by Devinci297** [comment]
> This is 3.6.16 and nothing..i try install by the zip and nothing shows up (not sure what the name displayed is list is supposed to be but not found to tick it. Tried to paste in scripts addon and it show up in Capital letters? but don't see it in list to tick. I changed all property to access for everyone in all Blender 3.3/3.6.16 and tried 4.2 but nothing (install by disk and zip file).
> 
The name displayed in Blender should be MSFS LOD Maker. I uploaded a new zip for version 0.1.4, try it again (You were still using version 0.1.3). You shouldn't have to change any permissions.

<img width="562" height="368" alt="Image" src="https://github.com/user-attachments/assets/ec7ba80e-a5bc-4268-a748-2ddf2827a21a" />

**Comment by UNC1RLM** [comment]
This is what I got when attempting to tick it. Had to shoot picture for you to see the message

![Image](https://github.com/user-attachments/assets/f1505657-4b0a-4ca5-b382-3ef8f7e63729)

**Comment by UNC1RLM** [comment]
![Image](https://github.com/user-attachments/assets/766193ef-52c7-4c9f-a48b-b9ec74179c09)

**Comment by Devinci297** [comment]
> This is what I got when attempting to tick it. Had to shoot picture for you to see the message
> 
Try again, there was an error in the file structure. I tried this zip personally and it works.

<img width="876" height="561" alt="Image" src="https://github.com/user-attachments/assets/2ed4caab-6a73-4ca9-91db-a23a7ee5e0cb" />

**Comment by UNC1RLM** [comment]
Do I need to redownload zip?

**Comment by UNC1RLM** [comment]
Get the same error as before but with new name. I look at your fol

<img width="963" height="419" alt="Image" src="https://github.com/user-attachments/assets/a954e14e-3b3b-4c5c-9c33-bb9b593e19b2" />

der and went to mine in app data and this is what is showing

**Comment by UNC1RLM** [comment]
![Image](https://github.com/user-attachments/assets/c490ad52-10e0-4d77-85a8-808a1f150c30)

**Comment by UNC1RLM** [comment]
I tried the source code zip which is 56KB verus original  27KB

**Comment by Devinci297** [comment]
> I tried the source code zip which is 56KB verus original 27KB
>
Please download the release here: [https://github.com/Devinci297/MSFS-LOD-Maker/releases/tag/v0.1.4](https://github.com/Devinci297/MSFS-LOD-Maker/releases/tag/v0.1.4 )
and try again

**Comment by UNC1RLM** [comment]
Finally but when I press "N"  will it show up. Will it work on later than 3.6.16?

<img width="2039" height="1029" alt="Image" src="https://github.com/user-attachments/assets/8358fe80-4fcd-4fa2-82b5-734f1955555f" />

You need to do a video on how to use it :)  You will be a hero at MSFS if this solves the problem of disappearing objects.  If you share it on Flightsim.to and set up a donate button and I will donate

**Comment by Devinci297** [comment]
> Finally but when I press "N" will it show up. Will it work on later than 3.6.16?
> 
> You need to do a video on how to use it :) You will be a hero at MSFS if this solves the problem of disappearing objects. If you share it on Flightsim.to and set up a donate button and I will donate

There are some instructions (although outdated) on the main page, but you don't open it with N, it's located in the Scene Properties panel. You can see it on my previous image

**Comment by UNC1RLM** [comment]
Have you successfully used this on objects in MSFS 2024?....where do i send the check :)

**Comment by Devinci297** [comment]
> Have you successfully used this on objects in MSFS 2024?....where do i send the check :)

This should work for either MSFS2020 or 2024, but the LOD values you put in xml will be different because of the new method for MSFS2024. These are unrelated to the plugin's operations though.

Cheers,

**Comment by UNC1RLM** [comment]
last question and I won't bother you.. will this put the values in for you or do we have to enter the values in the xml if I make since. Thank you!!! from a 75 year old flight enthusiast!!

**Comment by Devinci297** [comment]
> last question and I won't bother you.. will this put the values in for you or do we have to enter the values in the xml if I make since. Thank you!!! from a 75 year old flight enthusiast!!

No problem, if you're using the multi-export addon of MSFS20/24 it can put some values for you that it auto calculated but really, I think it's better to it manually to tweak the LODs are you need. The new MSFS2024 system has complicated things too much.

Best Regards,

**Comment by UNC1RLM** [comment]
After your program generates the lod's..is there a way to copy or get those figures because in the exporter it doesn't show any values

<img width="983" height="961" alt="Image" src="https://github.com/user-attachments/assets/6a755974-f4e3-418c-bbd9-2f6ab337d4be" />

**Comment by Devinci297** [comment]
> After your program generates the lod's..is there a way to copy or get those figures because in the exporter it doesn't show any values
> 
It looks like that feature is broken in the current plugin, I'll try to fix it for the next update. But as a general when it comes to MSFS2024 (only), you should use the value to 4 for LOD00, 3 for LOD01, 2 for LOD02, 1 for LOD00 as recommended by Asobo.
See here: [https://docs.flightsimulator.com/msfs2024/html/3_Models_And_Textures/Modeling/LODs/LOD_Selection_System.htm](url)

<img width="1218" height="565" alt="Image" src="https://github.com/user-attachments/assets/bcf8db03-eaf4-43a8-ad0c-f5da3874ac73" />

**Comment by UNC1RLM** [comment]
I am sending you three pics of what I have.... and I will load simulator and I believe I get a message about can't find lod00 bin or something..will send you a pic. Its late for you if in uk? Thank you so much for what you have done..amazing..just gotta get it to work :)

<img width="1505" height="1015" alt="Image" src="https://github.com/user-attachments/assets/ee2fdc39-d539-4b58-95f4-68eff9bae1bd" />
<img width="1679" height="1032" alt="Image" src="https://github.com/user-attachments/assets/646bd347-e14e-47cc-aa59-88b615ff354f" />
<img width="1359" height="430" alt="Image" src="https://github.com/user-attachments/assets/2a130809-a8bb-445a-9bbc-606a2a41911c" />

**Comment by UNC1RLM** [comment]
Doc page from asobo not loading

**Comment by Devinci297** [comment]
> I am sending you three pics of what I have.... and I will load simulator and I believe I get a message about can't find lod00 bin or something..will send you a pic. Its late for you if in uk? Thank you so much for what you have done..amazing..just gotta get it to work :)
> 
This is beyond the scope of the plugin. Your export workflow is not correct as it's not generating the .bin files. Also all your gltf files are only 1KB.  Your LOD003 collection looks to be empty so you should uncheck it. Is this your first time exporting for the Sim?

**Comment by UNC1RLM** [comment]
have exported several .. but i can zoom in and see but when I back up a little it disappears. I don't expect you to spend all your time on this.,. I appreciate all your help.. These were objects created for 2020  and trying to get into 2024

**Comment by UNC1RLM** [comment]
Got to go do honey do... getting tired..lol and I know you are.. So I will deal with it later. greets and Best Regard

**Comment by Devinci297** [comment]
> have exported several .. but i can zoom in and see but when I back up a little it disappears. I don't expect you to spend all your time on this.,. I appreciate all your help.. These were objects created for 2020 and trying to get into 2024

That disappearance is because of the new LOD system in 2024, it's not only the LOD values that matters but the number of vertices of each subsequent LOD has to be quite a bit less than the previous (like 50%). Otherwise it creates this issue. If you read the SDK doc I shared earlier it explains it into more detail. Maybe you can ask about it on fsdeveloper forum as to be honest I still don't understand it myself. The amount of work required to convert LOD objects from 2020 to 2024 has discouraged me from converting my scenery to it so far. 
Good Luck

**Comment by UNC1RLM** [comment]
Yeah..i have read till i am blue in the face.
Lol...i post on fs developer as "unc1rlm".
I post and I talk to rhumbaflappy..
but there probably tired of me. I am stubborn as he'll and sooner or later
I'll get it.
Thanks so much!!
